<a href="https://colab.research.google.com/github/Sana-Allah-Kheiri/jupyterlab/blob/main/kaggle_externalib_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import math
import numpy as np
#Lesson 1: external libraries are set of packages
# and Python Packages are .py files
#we want to see type of random submodule
print('Type of NumPy is ' , type(np));
print('Type of Random subModule is ' , type(np.random));
print('Random submodule contains:' , dir(np.random))
help(np.random.randint)



Type of NumPy is  <class 'module'>
Type of Random subModule is  <class 'module'>
Random submodule contains: ['BitGenerator', 'Generator', 'MT19937', 'PCG64', 'PCG64DXSM', 'Philox', 'RandomState', 'SFC64', 'SeedSequence', '__RandomState_ctor', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '_bounded_integers', '_common', '_generator', '_mt19937', '_pcg64', '_philox', '_pickle', '_sfc64', 'beta', 'binomial', 'bit_generator', 'bytes', 'chisquare', 'choice', 'default_rng', 'dirichlet', 'exponential', 'f', 'gamma', 'geometric', 'get_bit_generator', 'get_state', 'gumbel', 'hypergeometric', 'laplace', 'logistic', 'lognormal', 'logseries', 'mtrand', 'multinomial', 'multivariate_normal', 'negative_binomial', 'noncentral_chisquare', 'noncentral_f', 'normal', 'pareto', 'permutation', 'poisson', 'power', 'rand', 'randint', 'randn', 'random', 'random_integers', 'random_sample', 'ranf', 'rayleigh', 'sample', 'seed', 's

# Now lets toss a dice 10 times using np.random built-in function : randint

In [20]:
DiceTopNumbers = np.random.randint(low = 1 , high = 6 , size = 20 )
print(DiceTopNumbers)
print ('What is DiceTopNumbers?' , type(DiceTopNumbers));
print ('What RandInt submodule can do?' , dir(DiceTopNumbers));
print('Average of dice numbers: ', DiceTopNumbers.mean());
DiceTopNumbers.tolist();
print('List of Dice tossing results:',DiceTopNumbers);
print('Type of DiceTopNumbers is = ' , type(DiceTopNumbers.tolist()) );

[2 1 2 3 2 4 4 2 2 1 5 1 5 4 1 2 5 5 3 5]
What is DiceTopNumbers? <class 'numpy.ndarray'>
What RandInt submodule can do? ['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_namespace__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__buffer__', '__class__', '__class_getitem__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__dlpack__', '__dlpack_device__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '

array([ True,  True,  True,  True,  True, False, False,  True,  True,
        True, False,  True, False, False,  True,  True, False, False,
        True, False])

# Customized Data-Types are not Python's built-in data types, for example data frames & series(in Pandas). In MatPlotLib, you will see data types such as 1.Annotations or comments next to axis, 2. Subplots, 3. Figures & 4.TickMarks
# Now lets overload (positive) operator to make it act as an appending function, so wen you add <int> to a <list> , it appends <int> to <list>

In [26]:
rolls = np.random.randint(low = 1 , high = 6 , size = 10)
print(rolls)
print(rolls+3);
print(rolls<=3);

[4 4 5 1 3 2 1 2 5 3]
[7 7 8 4 6 5 4 5 8 6]
[False False False  True  True  True  True  True False  True]


Now lets convert matrix to an nd(N-Domensional) array so we can deal with multi-dimensional data & to access elements of array with indices

In [31]:
m = [[1,2,3] , [2,4,6]];
print('first element in M list is: ' , m[0]);
print('type of my matrix:', type(m));
m1 = np.asarray(m);
print('type of my matrix:', type(m1));
print ('last element of first record is ' , m1[0,-1]);

first element in M list is:  [1, 2, 3]
type of my matrix: <class 'list'>
type of my matrix: <class 'numpy.ndarray'>
last element of first record is  3


When does 1 + 1 not equal 2 ?!!!
exp: if these 1s are defined as strings they might be concatinated so the '1' + '1' will be '11' or more weird things like adding constants in TensorFlow

In [33]:
import tensorflow as tf
a = tf.constant(1);
b = tf.constant(1);
print(a+b);
print(type(a+b));

tf.Tensor(2, shape=(), dtype=int32)
<class 'tensorflow.python.framework.ops.EagerTensor'>
